apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - security.yaml
commonLabels: { app: aegis-gateway }
images:
  - name: aegis-gateway
    newName: ghcr.io/dgexplores/aegis-gateway
    newTag: latest
